OffTick Solution/System/Web/OfftickWeb/Areas/User/Controllers/OfferController.cs
using Offtick.Business.Membership;
using Offtick.Business.Services;
using Offtick.Business.Services.Managers;
using Offtick.Business.Services.RealtimeSearvices;
using Offtick.Business.Services.RealtimeSearvices.EventDrivenDispatcher.Notification;
using Offtick.Business.Services.Storage;
using Offtick.Business.Web;
using Offtick.Core.EnumTypes;
using Offtick.Core.Utility.PersianTools;
using Offtick.Data.Entities.Common;
using Offtick.Web.OfftickWeb.Areas.User.Models;
using Offtick.Web.OfftickWeb.Infrustracture;
using Offtick.Data.Context.ExpertOnlinerContexts;
using PaymentGatewayService;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Reflection;
using System.Web;
using System.Web.Mvc;

namespace Offtick.Web.OfftickWeb.Areas.User.Controllers
{
    public class OfferController : BaseController
    {
        public OfferController(DataContextContainer obj)
            : base(obj)
        {

        }


        //
        // GET: /User/Offers/

        public ActionResult Index()
        {
            return View();
        }

     

        #region Offtick_Offer
        [Authorize]
        public ActionResult OfftickOffer(string offtickOfferType)
        {
            ViewData["offtickOfferType"] = offtickOfferType;
            return View();
        }
        [Authorize,HttpPost]
        public ActionResult OfftickOffer(FoodModel model)
        {
            var currentUser = MembershipManager.Instance.GetCurrentUser();



            
            if (model!=null && ModelState.IsValid)
            {
                ChatService chatService = new ChatService();
                var response = chatService.SRpcSendOffer(new Business.Services.RealtimeSearvices.EventDrivenDispatcher.Notification.OfferNotification()
                {
                    Title = model.foodTitle,
                    Body = model.foodTitleLong,
                    Datetime = DateTime.Now.ToString(),
                    FromUserName = currentUser.UserName,
                    ToUserName = currentUser.UserName,
                    OfferType = (short)EnumOfferType.Food,
                });

                if (response.ResultStatus == "Success")
                {

                    string newFileName = string.Empty;
                    var responseEdit = OfferManager.Instance.UploadOfferFile(currentUser.UserName, response.DataObject.ToString(),model.mainImage, out newFileName);
                    if (responseEdit == Core.EnumTypes.EditStatus.Edited)
                    {
                        Guid offerId = Guid.Parse(response.DataObject.ToString());
                        var offer = OfferManager.Instance.GetOffer(offerId);
                        string foodSpecification = string.Empty;
                        string foodConditions = string.Empty;
                        string foodDescriptions = string.Empty;
                        Guid foodLocationCityId;
                        bool hasCityId=Guid.TryParse(model.foodLocationCityId,out foodLocationCityId);
                        if (model.foodSpecification != null && model.foodSpecification.InputStream != null)
                        {
                            System.IO.TextReader fileReader = new System.IO.StreamReader(model.foodSpecification.InputStream);
                            foodSpecification = fileReader.ReadToEnd();
                        }
                        if (model.foodConditions != null && model.foodConditions.InputStream != null)
                        {
                            System.IO.TextReader fileReader = new System.IO.StreamReader(model.foodConditions.InputStream);
                            foodConditions = fileReader.ReadToEnd();
                        }
                        if (model.foodDescriptions != null && model.foodDescriptions.InputStream != null)
                        {
                            System.IO.TextReader fileReader = new System.IO.StreamReader(model.foodDescriptions.InputStream);
                            foodDescriptions = fileReader.ReadToEnd();
                        }
                        var addStatus= OfferManager.Instance.AddFoodOffer(offer
                            , model.foodImages
                            , model.menuImages
                            , model.foodOriginalPrice
                            , model.foodOriginalTitle
                            , model.url
                            , model.foodUnit
                            , model.foodDiscountPrice
                            , model.foodDiscountTitle
                            , model.foodDiscountPercent
                            , model.foodExpireDate
                            , model.foodQuantity
                            , model.foodAudeiences
                            , foodSpecification
                            , foodConditions
                            , foodDescriptions
                            , hasCityId? (Guid?) foodLocationCityId:null
                            ,model.foodLocationAddress
                            ,model.offtickOfferTypeId
                            ,model.showIncomeInPercentage
                            ,model.foodHasAddedValueTax?(Nullable<short>) GeneralHelper.GetTaxValueForCurrentYear():null,
                            GeneralHelper.isConfirmedCompanyOfferOnInsert()?ConfirmStatus.Confirmed:ConfirmStatus.NotConfirmed
                            );

                       if(addStatus==AddStatus.Added)
                           return Json(new ActionResponseFromServerToClient(ActionResponseFromServerToClientResultStatusEnum.Success, "", "", newFileName, ""));
                    }
                }
            }
            return Json(new ActionResponseFromServerToClient(ActionResponseFromServerToClientResultStatusEnum.Failed, "Failed , try it again", "", "", "")); 
 
            
        }

        //[Authorize]
        public ActionResult OfftickOfferViewer(Offer offer)
        {
            if (offer!=null)
            {
                return View(offer);
            }
            return View();
        }

        public ActionResult MainPageBigOfferViewer()
        {
            return View(OfferManager.Instance.GetMaingPageBigOffer());
        }
        
        public ActionResult SaleFoodOffer(string userName, string offerId,string saleReferenceId, short count,long saleOrderId,bool isBuyingVisible=true)
        {
            Guid entityId;
            if (Guid.TryParse(offerId, out entityId))
            {
                var offer = OfferManager.Instance.GetOffer(entityId);
                var user=MembershipManager.Instance.GetUser(userName);
                if(OfferManager.Instance.isExpiredFoodOffer(offer))
                    return Json(new ActionResponseFromServerToClient(ActionResponseFromServerToClientResultStatusEnum.Failed, "Can not process your order, this offer has epired", string.Empty, string.Empty, ActionResponseFromServerToClient.EmptyObjectServerToClientKey));

                var actionStatus = OfferManager.Instance.OrderFoodOffer(offer, user, count, saleOrderId,saleReferenceId ,isBuyingVisible, Offtick.Web.OfftickWeb.Infrustracture.PdfServiceGenerator.CreateDefaultPdfService());
                if (actionStatus == AddStatus.Added)
                {
                    if (!string.IsNullOrEmpty(userName))
                    {
                        string messageBody = string.Format("user:{0} requests {1} units of {2}, mobile: {3}, email: {4}", user.FirstName + " " + user.LastName, count, offer.Title,user.PhoneNumber,user.Email);
                        var notification = new SendMessageNotification()
                        {
                            FromUserName = userName,
                            Message = messageBody,
                            ToUserName = offer.MembershipUser.UserName,
                            Flags = 1,
                            MessageType = "0"

                        };
                        ChatService chService = new ChatService();
                        chService.SRpcSendMessage(notification);


                        //start send sms one for saler and one for bayer
                        string baySaleDate = Offtick.Core.Utility.PersianTools.PersianDateConvertor.ToKhorshidiDate(DateTime.Now);

                        string salerName = offer.MembershipUser.FirstName;
                        var saleOfferNumber = saleOrderId;
                        var saleOfferPrice=offer.OfferFoods.FirstOrDefault().DiscountPrice * count;
                        string salerSms = string.Format(Resources.UIMessages.SmsSaleCompanyReportSuccess, salerName, saleOfferNumber, baySaleDate, saleOfferPrice, count);
                        string salerMobile = offer.MembershipUser.PhoneNumber;
                        
                        string bayerName = user.FirstName + " " + user.LastName;
                        var tracingNo = saleOrderId;
                        string bayerSms = string.Format(Resources.UIMessages.SmsSaleCustomerReportSuccess, bayerName, tracingNo, baySaleDate);
                        string bayerMobile = user.PhoneNumber;

                        Action actionSendSms = () =>
                        {
                            if(!string.IsNullOrEmpty( salerMobile))
                                Offtick.Business.Services.Domain.SmsService.Instance.SendMagfaSms(salerMobile,salerSms);
                            if (!string.IsNullOrEmpty(bayerMobile))
                                 Offtick.Business.Services.Domain.SmsService.Instance.SendMagfaSms( bayerMobile,bayerSms);
                        };
                        actionSendSms.BeginInvoke(null, null);
                        // end of send sms for saler and buyer
                        
                    }

OffTick Solution/System/Web/OfftickWeb/Controllers/ProfileController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Offtick.Web.OfftickWeb.Controllers
{
    public class ProfileController : Controller
    {
        //
        // GET: /Profile/

        public ActionResult Index()
        {
            return View();
        }

    }
}

OffTick Solution/System/Web/OfftickWeb/Areas/User/Views/Offer/CommentsForOfferModal.cshtml
@model Offtick.Web.OfftickWeb.Areas.User.Models.OfferVisitedPresenterModel
@{if(Model!=null)
  {
    string modalMode="";
      switch(Model.ModalMode){
          case Offtick.Web.OfftickWeb.Areas.User.Models.ModalMode.large:
              modalMode = "modal-lg";
              break;
          case Offtick.Web.OfftickWeb.Areas.User.Models.ModalMode.Small:
              modalMode = "modal-sm";
              break;
          case Offtick.Web.OfftickWeb.Areas.User.Models.ModalMode.Medium:
              modalMode = "modal-md";
              break;
      }
      
      var offer=Offtick.Business.Services.Managers.OfferManager.Instance.GetOffer(Model.OfferId);
      
      if(offer!=null){
          var offerVisiteds=offer.OfferVisiteds;
            <!-- Modal -->
            <div id="@Model.ControlId" class="modal fade" role="dialog" tabindex='-1'>
              <div class="modal-dialog @modalMode">

                <!-- Modal content-->
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title text-center">@Model.HeaderTitle</h4>
                  </div>
                  <div class="modal-body text-left">
                        @Html.Action("CommentsForOffer","Offer",new {area="User",offer=offer}) 
                  </div>
                </div>

              </div>
            </div>
        }
    }
}

OffTick Solution/System/Web/OfftickWeb/Areas/User/Views/Offer/MainPageBigOfferViewer.cshtml
@model Offtick.Data.Context.ExpertOnlinerContexts.Offer


@{
   
    
 if(Model!=null){
     var offer = Model;
     Layout = "";



     var currentUser = Offtick.Business.Membership.MembershipManager.Instance.GetCurrentUser();

     var currentUserName = string.Empty;
     string roleName = string.Empty;
     Offtick.Data.Context.ExpertOnlinerContexts.MembershipUsersInRole roleOfUser = null;
     var thumbnailOfCurrentUser = string.Empty;
     if (currentUser != null)
     {
         currentUserName = currentUser.UserName;
         roleOfUser = currentUser.MembershipUsersInRoles.FirstOrDefault();
         if (roleOfUser != null)
         {
             roleName = roleOfUser.MembershipRole.RoleName;
         }
         thumbnailOfCurrentUser = Offtick.Web.OfftickWeb.Infrustracture.GeneralHelper.GetThumbnailOf(currentUser.UserId, currentUser.Picture);
     }




     //var offers = Offtick.Business.Services.Managers.OfferManager.Instance.getWallOffersForUser(currentUser, 0, 20);





     var urlOfCurrentUserProfile = Url.Action("Index", "Profile", new { area = "User" });


     string userNameOfOfferOwner = offer.MembershipUser.UserName;
     Guid userIdOfOfferOwner = offer.MembershipUser.UserId;
     var userFileManager = new Offtick.Business.Services.Storage.File.ImageFileManager(userIdOfOfferOwner.ToString());
     string urlOfOfferOwner = Offtick.Web.OfftickWeb.Infrustracture.GeneralHelper.GetThumbnailOf(userIdOfOfferOwner, offer.MembershipUser.Picture);
     var urlOfImage = userFileManager.GetRelativeFullFileName(userIdOfOfferOwner.ToString(), offer.FileName, false);
     var foodOffer = offer.OfferFoods.FirstOrDefault();
     var foodOfferImages = foodOffer != null ? foodOffer.OfferFoodImages.Where(e => e.ImageType == (short)Offtick.Business.Services.Managers.FoodOfferImageType.FoodImage).ToList() : null;

     bool isOfferLiked = Offtick.Business.Services.Managers.OfferManager.Instance.IsOfferLikedByUser(currentUser, offer);
     var likeCssClass = isOfferLiked ? "fa fa-heart liked" : "fa fa-heart-o unLiked";
    <div class="row"  >
     
        
       
              
        @*  <a href="@Url.Action("OfferViewer", "Offer", new { area = "User", offerId = offer.OfferId })">
                    <img src="@urlOfImage" style="max-width:1000px;max-height:500px;"/>
            </a>*@
        <div class="col-md-7">
          
            <div class="row">
                @if (foodOfferImages != null && foodOfferImages.Count > 0)
                {
                    <div id="foodCarousel" class="carousel slide" data-ride="carousel">
                      <!-- Indicators -->
                      <ol class="carousel-indicators">
                          @for (int i = 0; i < foodOfferImages.Count; i++)
                          {
                              string classStr= i==0?"class='active'":string.Empty;
                                <li data-target="#foodCarousel" data-slide-to="@i" @classStr></li>
                          }
                      </ol>

                      <!-- Wrapper for slides -->
                          <div class="carousel-inner " role="listbox"  >
    
     

                            @for (int i = 0; i < foodOfferImages.Count; i++)
                            {
                                var galleryImage = foodOfferImages[i];
                                string classStr = i == 0 ? "active" : string.Empty;
                                string imgUrl = Offtick.Business.Services.Managers.GalleryManager.Instance.GetVirtualPathOfGalleryImage(galleryImage.Name, userNameOfOfferOwner, false);


                               <div class="item @classStr" >
                                    <img src="@imgUrl"  style="margin: auto; max-width:400px;  max-height:400px;" >
                                      <div class="carousel-caption">
                                       @* <h3>@galleryImage.Title</h3>*@
                                        <p>@galleryImage.Description</p>
                                      </div>
                                 </div>
                            }
   


                          <!-- Left and right controls -->
                          <a class="left carousel-control" href="#foodCarousel" role="button" data-slide="prev">
                            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                            <span class="sr-only">Previous</span>
                          </a>
                          <a class="right carousel-control" href="#foodCarousel" role="button" data-slide="next">
                            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                            <span class="sr-only">Next</span>
                          </a>
                        </div>
                    </div>
                }
            </div>
                    
            <div class="row">
                <div class="col-md-1 col-md-offset-1">
                    @*<span class="fa fa-heart likeOfferCount">@offer.OfferLikes.Count()</span>*@
                    @{
                        string controlId=Guid.NewGuid().ToString();
                    }

                    <span class="btn btn-warning btn-xs fa fa-eye " data-toggle="modal" data-target="#@controlId">@foodOffer.ViewCount</span>

                    @Html.Action("OfferVisitedPresenter","Offer",new {area="User",offerId=offer.OfferId,controlId=controlId,pictureSize=64,headerTitle="مشاهده اشخاص بازدیدکننده", modalMode=Offtick.Web.OfftickWeb.Areas.User.Models.ModalMode.Medium})
                </div>
                <div class="col-md-1 col-md-offset-8">
                   @* <span class="fa fa-comment commentOfferCount">@offer.OfferComments.Count()</span>*@

                        @{
                            string baseControlId=Guid.NewGuid().ToString();
                            string viewControlId="view"+baseControlId;
                            string commentControlId = "comment" + baseControlId;
                        }
                       <span class="btn btn-warning btn-xs fa fa-comment" style="padding-left:10px;" data-toggle="modal" data-target="#@commentControlId"> @offer.OfferComments.Count</span>
                        @Html.Action("CommentsForOfferModal","Offer",new {area="User",offerId=offer.OfferId,controlId=commentControlId,pictureSize=64,headerTitle="مشاهده اشخاص نظردهنده", modalMode=Offtick.Web.OfftickWeb.Areas.User.Models.ModalMode.large})

                </div>
            </div>
        </div>

        <div class="col-md-5">
            <div class="well">
        
               <div class="row text-center text-bold">
                   <p style="padding-top:5px;padding-bottom:5px;" class="h4">
                       @offer.Body
                    </p>
                       @offer.MembershipUser.LastName

                </div>
                <div class="row text-center">
                    <span class="col-md-6  text-danger">
                        @foodOffer.DiscountPercent %
                    </span>
                     <span class="col-md-6 text-center text-danger">
                        @foodOffer.DiscountPriceTitle
                         <br />
                                                  <span>  @foodOffer.DiscountPrice </span>

                         <span >@foodOffer.DiscountPriceUnit</span>
                    </span>
                </div>

            @{
                var buyOrders=foodOffer.OfferFoodOrders.OrderByDescending(e=>e.DateTime).Take(7);
               
                    <div class="panel">

                        <div class="panel-body  text-right">
                             <span class="text-success h4 "> خریداران</span>
                          <br />

                            @foreach (var offerFoodOrder in buyOrders)
                                {
                                    @Html.Action("ShowUserStatus", "Profile", new { area = "User", user = offerFoodOrder.MembershipUser,maxWidth=32 });
                                }

                        </div>
                
                    </div>
                
            }
                <div class="row text-center" style="margin-top:25px;">
                      <span class="col-md-4 text-primary">
                        @foodOffer.OriginalPriceTitle
                         <br />
                         <span> <del>@foodOffer.OriginalPrice </del> </span>

                         
                    </span>            
                      @{
                            var countOfSoled = foodOffer.OfferFoodOrders.Sum(e => e.Quantity);
                            var countOfOffer = foodOffer.Quantity;

                            var remain = countOfOffer - countOfSoled;

                        }
                    <span class="col-md-4 text-warning">
                        <span class="fa fa-shopping-cart text-info"></span>
                        <br />
                        @countOfSoled
                    </span>
                   
                    <span class="col-md-4 text-warning">
                      
                        :باقی مانده
                        <br />
                        @remain
                    </span>
                   
                </div>
                <span class="text-right col-md-12 ">
                    
                    @offer.MembershipUser.Address
                    <span class="fa fa-map-marker text-info"></span>
                </span>
                
            </div>
          
            <div class="panel panel-default row" style="margin:10px; padding:10px;">
                
                <a href="@Url.Action("OfferViewer","Offer",new{area="User",offerId=Model.OfferId})">
                    <span class=" btn btn-success col-md-12 padding3 btn-md" >
                        مشاهده جزییات و خرید
                    </span>
                </a>
            </div>
        </div>
    </div>
}   
}

OffTick Solution/System/Web/OfftickWeb/Areas/User/Views/Offer/OfferManagementCombo.cshtml
@using Offtick.Web.OfftickWeb.Infrustracture;
@{
    string userNameOfOfferOwner = ViewBag.userNameOfOfferOwner;
    string currentUserName = ViewBag.currentUserName;
    string roleName=GeneralHelper.GetRoleName(GeneralHelper.GetCurrentUser());

}  
  <div class="edit-icon">
    <i class="fa fa-cog" aria-hidden="true"></i>
    <ul data-offerId="@ViewBag.offerId">
        <li><span class="btn fa fa-eye reportOffer">  گزارش  </span></li>
         @if (!string.IsNullOrEmpty(userNameOfOfferOwner) && !string.IsNullOrEmpty(currentUserName) && (userNameOfOfferOwner.Equals(currentUserName) || roleName=="Administrator"))
        {
            <li><span class="btn fa fa-trash-o deleteOffer">  حذف  </span></li>
            <li class="divider"></li>
            <li><span  class="btn fa fa-wrench editOffer">  تنظیمات  </span></li>
             <li class="divider"></li>
             <li><span  class="btn fa fa-pencil-square-o upgradeOffer">  ویرایش  </span></li>
        }
    </ul>
</div>
    

OffTick Solution/System/Web/OfftickWeb/Areas/User/Views/Offer/OfferVisitedPresenter.cshtml
@model Offtick.Web.OfftickWeb.Areas.User.Models.OfferVisitedPresenterModel
@{if(Model!=null)
  {
    string modalMode="";
      switch(Model.ModalMode){
          case Offtick.Web.OfftickWeb.Areas.User.Models.ModalMode.large:
              modalMode = "modal-lg";
              break;
          case Offtick.Web.OfftickWeb.Areas.User.Models.ModalMode.Small:
              modalMode = "modal-sm";
              break;
          case Offtick.Web.OfftickWeb.Areas.User.Models.ModalMode.Medium:
              modalMode = "modal-md";
              break;
      }
      
      var offer=Offtick.Business.Services.Managers.OfferManager.Instance.GetOffer(Model.OfferId);
      
      if(offer!=null){
          var offerVisiteds=offer.OfferVisiteds;
            <!-- Modal -->
            <div id="@Model.ControlId" class="modal fade" role="dialog" tabindex='-1'>
              <div class="modal-dialog @modalMode">

                <!-- Modal content-->
                <div class="modal-content">
                  <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                    <h4 class="modal-title text-center">@Model.HeaderTitle</h4>
                  </div>
                  <div class="modal-body text-left">
                      @{
                          bool showViewers= offer.OfferPrivacy!=null? offer.OfferPrivacy.IsViewerVisible:true;
                      }
                      @if(showViewers){
                          foreach(var offerVisited in offerVisiteds){
                          var userPrivacy=offerVisited.MembershipUser.MembershipPrivacy;
                              if(userPrivacy!=null && userPrivacy.IsViewingVisible){
                                @Html.Action("ShowUserStatus", "Profile", new { area = "User", user = offerVisited.MembershipUser,maxWidth=@Model.PictureSize });
                                    }
                          }
                      }else
                      {
                          <span class="text-right">مشاهده بازدیدکنندگان این آفر غیر فعال می باشد.</span>
                      }
            
                  </div>
                  @*<div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                  </div>*@
                </div>

              </div>
            </div>
        }
    }
}

OffTick Solution/System/Web/OfftickWeb/Areas/User/Views/Offer/PostPhoto.cshtml
@model Offtick.Web.OfftickWeb.Areas.Dr.Models.AdaptGalleryModel 
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
    string actionUrl = Url.Action("PostPhotoLoader", "Offer", new { area = "User" });

    string guid=Guid.NewGuid().ToString();
    string txtTitleId = "txtTitle" + guid;
    string txtDescriptionId = "txtDescriptionId" + guid;
    string btnSendId = "btnSend" + guid;
    string fileUploadId = "fileUpload" + guid;
        
}

   <script src="@Url.Content("~/Scripts/Local/ShowImageOnClientBeforeUploading.js")" type="text/javascript"></script>


<div class="main-wrapper single-page">
            <section class="layout">
                <article>
                    <header class="article-header">

                        <h3>بارگزاری عکس</h3>

                    </header>
                    <div>
                           <label for="@fileUploadId" class="btnB"> انتخاب عکس</label>
                            <br /> <br />
                            <img src="" id="imgFilePicture" style="max-height:160px;max-width:160px"  />
                            <input type="file" name="@fileUploadId" id="@fileUploadId" onchange="fileSelected();" title="Select File" style="display:none;"  accept="image/*" />
                            <div id="fileName"></div>
                            <div id="fileSize"></div>
                           <br />
                        @Html.TextBoxFor(e => e.Title, new { id = txtTitleId ,placeholder="Title:",@class="w-6"})
                            <br />
                        @Html.TextBoxFor(e => e.Description, new { id = txtDescriptionId ,placeholder="Say somethings about this picture:",@class="w-6"})

                        <br />
                        <input type="button" onclick="uploadFile()" value="Post" class="btnB w-1"  />
                        <br />
                        <div id="progressContainerUploadImageOffer" class="progress hide">
                          <div class="progress-bar progress-bar-success" role="progressbar" 
                          aria-valuemin="0" aria-valuemax="100" style="width:40%" id="uploadProgressBar">
                            
                          </div>
                        </div>
                    </div>
                </article>
            </section>
        </div>
        <!--main-wrapper-->


    <script type="text/javascript">
        imageBeforeUploading("@fileUploadId", "imgFilePicture",false);

        function fileSelected() {
            var file = document.getElementById('@fileUploadId').files[0];
            if (file) {
                var fileSize = 0;
                if (file.size > 1024 * 1024)
                    fileSize = (Math.round(file.size * 100 / (1024 * 1024)) / 100).toString() + 'MB';
                else
                    fileSize = (Math.round(file.size * 100 / 1024) / 100).toString() + 'KB';

                document.getElementById('fileName').innerHTML = 'File Name: ' + file.name;
                document.getElementById('fileSize').innerHTML = 'File Size: ' + fileSize;
                
            }
        }

        function uploadFile() {
            if (document.getElementById('@fileUploadId').files.length == 0) {
                alert("فایل نمی تواند خالی باشد.");
                return;
            }
            $("#progressContainerUploadImageOffer").removeClass("hide");
            var fd = new FormData();
            fd.append("@fileUploadId", document.getElementById('@fileUploadId').files[0]);
            fd.append("Title", $("#@txtTitleId").val());
            fd.append("Description", $("#@txtDescriptionId").val());
         

            var xhr = new XMLHttpRequest();
            xhr.upload.addEventListener("progress", uploadProgress, false);
            xhr.addEventListener("load", uploadComplete, false);
            xhr.addEventListener("error", uploadFailed, false);
            xhr.addEventListener("abort", uploadCanceled, false);
            xhr.open("POST", "@actionUrl", true);
            
            xhr.send(fd);
        }

        function uploadProgress(evt) {
            if (evt.lengthComputable) {
                var percentComplete = Math.round(evt.loaded * 100 / evt.total);
                $("#uploadProgressBar").html(percentComplete + "% uploading");
                $("#uploadProgressBar").attr("aria-valuenow", percentComplete);
                $("#uploadProgressBar").css("width", percentComplete+"%");
               // document.getElementById('progressNumber').innerHTML = percentComplete.toString() + '%';
            }
            else {
                document.getElementById('progressNumber').innerHTML = 'unable to compute';
            }
        }

        function uploadComplete(evt) {
            /* This event is raised when the server send back a response */
           
            //alert(evt.target.responseText);
            var serverToClientResponse = JSON.parse( evt.currentTarget.response);
            if (serverToClientResponse) {
                if (serverToClientResponse.ResultStatus == "Success") {
                  
                    $("#fileName").empty();
                    $("#fileSize").empty();
                    $("#progressNumber").empty();
                    var redirectSuccessUrl = "@Url.Action("Wall","Profile",new {area="User"})";
                    $(location).attr('href', redirectSuccessUrl);
                }
                else {
                    alert("fail to upload offer"+ " " + serverToClientResponse.Error);
                }
            }
            else {
                alert("fail to upload offer, make sure you are logined and try again");
            }
           
        }

        function uploadFailed(evt) {
            alert("There was an error attempting to upload the file.");
        }

        function uploadCanceled(evt) {
            alert("The upload has been canceled by the user or the browser dropped the connection.");
        }
    </script>