OffTick Solution/System/Web/OfftickWeb/Areas/Dr/Controllers/MenuBuilderController.cs
using Offtick.Business.Membership;
using Offtick.Business.Services.Managers;
using Offtick.Core.EnumTypes;
using Offtick.Data.Context.ExpertOnlinerContexts;
using Offtick.Web.OfftickWeb.Areas.Dr.Models;
using Offtick.Web.OfftickWeb.Infrustracture;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Offtick.Web.OfftickWeb.Areas.Dr.Controllers
{
    public class MenuBuilderController : Offtick.Business.Web.BaseController
    {


        public MenuBuilderController(Offtick.Business.Services.Storage.DataContextContainer obj)
            : base(obj )
        {
            
        }


        //
        // GET: /Dr/MenuBuilder/

        public ActionResult Index()
        {
            var currentUser = MembershipManager.Instance.GetCurrentUser();
            return View(currentUser != null ? currentUser.Menus.Where(e => e.ParentId == null) : null);
        }

        public ActionResult DeleteMenu(MenuBuilderGeneralModel model )
        {
            DeleteStatus status = MenuBuilder.Instance.DeleteMenu(model.MenuId.Value);
            string msg = UIActionStatusToUiMessage.ActionStatusToMessage(status);
            return Json(msg);
        }

        public ActionResult EditMenuInfo(MenuBuilderGeneralModel model)
        {
            EditStatus status= MenuBuilder.Instance.EditMenuTitle(model.MenuId.Value, model.Title);
            string msg = UIActionStatusToUiMessage.ActionStatusToMessage(status);
            return Json(msg);
        }

        public ActionResult AddMenu(Offtick.Data.Entities.Common.Models.MenuModel menu)
        {
            AddStatus status = MenuBuilder.Instance.AddMenu(menu.ParentId,
                LangaugeManager.Instance.GetDefaultLangaugeId(),
                menu.Title, (MenuType)menu.MenuType, menu.Url,menu.IconUrl, menu.IsSystemMenu);
            string msg = UIActionStatusToUiMessage.ActionStatusToMessage(status);
            return Json(msg);
        }

        public ActionResult MenuBuilderParser(Nullable<Guid> menuId)
        {
            return View("MenuBuilderBody", menuId.HasValue? MenuBuilder.Instance.GetMenu(menuId.Value):
                 new Menu() { LastDateTime = DateTime.Now, MenuType = (short)Offtick.Core.EnumTypes.MenuType.ParentMenu }
                );
        }

        public ActionResult AdaptMenuContent(Offtick.Web.OfftickWeb.Areas.Dr.Models.TextAreaModel model)
        {
            if (model.CommandType == CommandType.Add)
            {
                AddStatus status = MenuBuilder.Instance.AddMenuContent(Guid.Parse( model.EntityId),LangaugeManager.Instance.GetDefaultLangaugeId(), model.Value);
                string msg = UIActionStatusToUiMessage.ActionStatusToMessage(status);
                return Json(msg);
            }
            else
            {
                EditStatus status = MenuBuilder.Instance.EditMenuContentByMenuId(Guid.Parse(model.EntityId), model.Value);
                string msg = UIActionStatusToUiMessage.ActionStatusToMessage(status);
                return Json(msg);
            }
        }
    }
}

OffTick Solution/System/Web/OfftickWeb/Areas/User/Controllers/MenuBuilderController.cs
using Offtick.Business.Membership;
using Offtick.Business.Services.Managers;
using Offtick.Core.EnumTypes;
using Offtick.Data.Context.ExpertOnlinerContexts;
using Offtick.Web.OfftickWeb.Areas.Dr.Models;
using Offtick.Web.OfftickWeb.Infrustracture;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Offtick.Web.OfftickWeb.Areas.User.Controllers
{
    [Authorize]
    public class MenuBuilderController : Offtick.Business.Web.BaseController
    {


        public MenuBuilderController(Offtick.Business.Services.Storage.DataContextContainer obj)
            : base(obj )
        {
            
        }


        //
        // GET: /Dr/MenuBuilder/

        public ActionResult Index()
        {
            var currentUser = MembershipManager.Instance.GetCurrentUser();
            return View(currentUser != null ? currentUser.Menus.Where(e => e.ParentId == null) : null);
        }

        public ActionResult DeleteMenu(MenuBuilderGeneralModel model )
        {
            DeleteStatus status = MenuBuilder.Instance.DeleteMenu(model.MenuId.Value);
            string msg = UIActionStatusToUiMessage.ActionStatusToMessage(status);
            return Json(msg);
        }

        public ActionResult EditMenuInfo(MenuBuilderGeneralModel model)
        {
            EditStatus status= MenuBuilder.Instance.EditMenuTitle(model.MenuId.Value, model.Title);
            string msg = UIActionStatusToUiMessage.ActionStatusToMessage(status);
            return Json(msg);
        }

        public ActionResult AddMenu(Offtick.Data.Entities.Common.Models.MenuModel menu)
        {
            AddStatus status = MenuBuilder.Instance.AddMenu(menu.ParentId,
                LangaugeManager.Instance.GetDefaultLangaugeId(),
                menu.Title, (MenuType)menu.MenuType, menu.Url,menu.IconUrl, menu.IsSystemMenu);
            string msg = UIActionStatusToUiMessage.ActionStatusToMessage(status);
            return Json(msg);
        }

        public ActionResult MenuBuilderParser(Nullable<Guid> menuId)
        {
            return View("MenuBuilderBody", menuId.HasValue? MenuBuilder.Instance.GetMenu(menuId.Value):
                 new Menu() { LastDateTime = DateTime.Now, MenuType = (short)Offtick.Core.EnumTypes.MenuType.ParentMenu }
                );
        }

        public ActionResult AdaptMenuContent(Offtick.Web.OfftickWeb.Areas.Dr.Models.TextAreaModel model)
        {
            if (model.CommandType == CommandType.Add)
            {
                AddStatus status = MenuBuilder.Instance.AddMenuContent(Guid.Parse( model.EntityId),LangaugeManager.Instance.GetDefaultLangaugeId(), model.Value);
                string msg = UIActionStatusToUiMessage.ActionStatusToMessage(status);
                return Json(msg);
            }
            else
            {
                EditStatus status = MenuBuilder.Instance.EditMenuContentByMenuId(Guid.Parse(model.EntityId), model.Value);
                string msg = UIActionStatusToUiMessage.ActionStatusToMessage(status);
                return Json(msg);
            }
        }
    }
}

OffTick Solution/System/Web/OfftickWeb/Areas/User/Views/MenuBuilder/Index.cshtml
@model IEnumerable<Offtick.Data.Context.ExpertOnlinerContexts.Menu>
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
    
  <link rel="stylesheet" href="@Url.Content("~/Content/themes/base/jquery-ui.css")" >
  <link rel="stylesheet" href="@Url.Content("~/Content/AdminStyleSheet.css")" >
    
    
    <script src="@Url.Content("~/Scripts/jquery-ui-1.12.0.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" ></script>
    
     <link type="text/css" href="@Url.Content("~/Content/apycom/yellow-green/menu.css")" rel="stylesheet" />
    <script type="text/javascript" src="@Url.Content("~/Content/apycom/yellow-green/menu.js")"></script>
    
    
     <link rel="stylesheet" href="@Url.Content("/Content/bootstrap.min.css")">
    <link rel="stylesheet" href="@Url.Content("/Content/LayoutStyle.css")">

    <script src="@Url.Content("~/Scripts/purl.js")"></script>
    <script src="@Url.Content("~/Scripts/bootstrap.min.js")"></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")"></script>

    
    var menuItem = Offtick.Business.Web.MvcMenu.MVCMenuBuilder.ConvertToMenuItem(Model);
}

<h2>Menu Builder</h2>
<style type="text/css">
    div#menu { margin:5px auto; }
</style>

<div id="MenuBuilderContainer">
    <div style="direction:ltr;text-align:left;">
         @Html.Raw(
        @Offtick.Business.Web.MvcMenu.MVCMenuBuilder.MvcMenuBuilder(menuItem,"parent","menu","","menu","DivMenuBuilderBody", Offtick.Business.Web.MvcMenu.MvcMenuType.JQueryDefault))
    </div>
    <div id="DivMenuBuilderBody">
        @Html.Partial("MenuBuilderBody", new Offtick.Data.Context.ExpertOnlinerContexts.Menu() { LastDateTime = DateTime.Now ,MenuType=(short)Offtick.Core.EnumTypes.MenuType.ParentMenu})
    </div>
</div>

OffTick Solution/System/Web/OfftickWeb/Areas/User/Views/MenuBuilder/MenuBuilderBody.cshtml
@model Offtick.Data.Context.ExpertOnlinerContexts.Menu

@{
    string tab2Title = Model == null || (Offtick.Core.EnumTypes.MenuType)Model.MenuType == Offtick.Core.EnumTypes.MenuType.ChildMenu ? "Edit Content" : "New Menu";
    string tab2PartialView = "MenuBuilderAddNewMenu";
    object modelObj = null;
    Offtick.Core.EnumTypes.CommandType commandType = Model.MenuId != default(Guid) && Model.MenuContents.Count>0? Offtick.Core.EnumTypes.CommandType.Edit : Offtick.Core.EnumTypes.CommandType.Add;
    
   if(Model!=null)
   {
       switch ((Offtick.Core.EnumTypes.MenuType)Model.MenuType)
        {
            case Offtick.Core.EnumTypes.MenuType.ChildMenu:
                tab2PartialView = "MenuBuilderChildHtmlEditor";
                string valueToEditor = commandType == Offtick.Core.EnumTypes.CommandType.Add ? string.Empty : Model.MenuContents != null ? Model.MenuContents.First().Body : string.Empty;
                string entityId = commandType == Offtick.Core.EnumTypes.CommandType.Add ? Model.MenuId.ToString() :Model.MenuContents.First().ContentId.ToString();
                modelObj = new Offtick.Web.OfftickWeb.Areas.Dr.Models.TextAreaModel() { EntityId = entityId, Title = "Please Enter Content Of Menu", Value = valueToEditor, CommandType = commandType, ActionUrl = Url.Action("AdaptMenuContent") };
                break;
            case Offtick.Core.EnumTypes.MenuType.DirectLink:
                tab2PartialView = "MenuBuilderNoAddingMenuToDirectLink";
                modelObj = null;
                break;
            case Offtick.Core.EnumTypes.MenuType.ParentMenu:
                tab2PartialView = "MenuBuilderAddNewMenu";
                modelObj = Model;
                break;
        }
   }
    
}

 
<div id="MenuBuilderHeaderInfoDiv">
    @Html.Partial("MenuBuilderHeaderInfo",Model)
</div>

 

<div id="MenuBuilderBodyTabs">
    <ul class="nav nav-tabs">
    <li class="active"><a data-toggle="tab" href="#menu_tab1">Edit Current menu</a></li>
    <li><a data-toggle="tab" href="#menu_tab2">@tab2Title</a></li>
  </ul>

      <div class="tab-content">
        <div id="menu_tab1" class="tab-pane fade in active">
            @Html.Partial("MenuBuilderEditMenuInfo",Model)
        </div>
        <div id="menu_tab2" class="tab-pane fade">
            @Html.Partial(tab2PartialView, modelObj)
        </div>
 
    </div>

 
</div>

OffTick Solution/System/Web/OfftickWeb/Areas/User/Views/MenuBuilder/MenuBuilderChildHtmlEditor.cshtml
@model Offtick.Web.OfftickWeb.Areas.Dr.Models.TextAreaModel
@{
    string modelValue = Model != null ? Model.Value : "";
    string btnSaveId = Model != null ? "btnSaveHtmlEditorValue" + Model.EntityId : "btnSaveHtmlEditorValue"+Guid.NewGuid().ToString();
}
<div class="AboutUs">

    <div class="TextHeader">
           <h3>@Model.Title</h3> 
    </div>


    @Html.TextArea("editor1",modelValue, new { @class = "ckeditor" })
 
       





<input type="button" id="@btnSaveId" value="Save" />
    </div>

     <script type="text/javascript">
         $(function () {
             CKEDITOR.replace('editor1');
             $("#@btnSaveId").click(function () {
                 
                 $(this).attr("disabled", true);

                 var postedData = { EntityId: "@Model.EntityId", Value: CKEDITOR.instances.editor1.getData(), CommandType: "@((short)Model.CommandType)" }
                 $.ajax({
                     type: 'POST',
                     url: '@Model.ActionUrl',
                     data: JSON.stringify(postedData),
                     dataType: 'json',
                     processData: false,
                     contentType: 'application/json; charset:utf-8',
                     success: function (data, status) {
                         //showCommunicationPanelMessage(data, 4000);
                         alert(data);
                         $(this).removeAttr("disabled");
                     },
                     error: function (xhr, textStatus, error) {
                         var errorMessage = error || xhr.statusText;
                         showCommunicationPanelMessage(errorMessage + textStatus, 4000);
                         $(this).removeAttr("disabled");
                         //  alert(errorMessage+ xhr.toString() + textStatus);
                     }
                 });
             });
         });
            </script>

OffTick Solution/System/Web/OfftickWeb/Areas/User/Views/MenuBuilder/MenuBuilderEditMenuInfo.cshtml
@model Offtick.Data.Context.ExpertOnlinerContexts.Menu
@{
    string menuId = Model != null ? Model.MenuId.ToString() : string.Empty;
    string sortableId="AddMenuBuilderEditMenuInfoSortable";
    IList<string> liCssClasses=new List<string>();
    liCssClasses.Add("ui-state-default");
    IList<string> liSpanContentCssClass=new List<string>();
    liSpanContentCssClass.Add("ui-icon ui-icon-arrowthick-2-n-s");
    string modelTitle = Model != null ? Model.Title : "";
    string actionUrl = Url.Action("Index", "MenuBuilder", new { area = "User" });
    
}
<style type="text/css">
     #@sortableId { list-style-type: none; margin: 0; padding: 0;  }
  #@sortableId li { margin: 0 3px 3px 3px; padding: 0.4em; padding-left: 1.5em; font-size: 1.4em; height: 18px; }
  #@sortableId li span { position: absolute; margin-left: -1.3em; }

</style>
<script type="text/javascript">
    $(function () {
        $("#btnMenuBuilderEditMenuInfoChangeOrder").click(function () {
            var sorted = $("#@sortableId").sortable("serialize", {expression: "(.+)_(.+)" });
            
            sorted = "{" + sorted.toString().split("&").join('",').split('Sort[]').join('"Sort').split("=").join('":"') + '"}';
            
            
            var jsonSorted = $.parseJSON(sorted);
            //alert(jsonSorted);
        });

        $("#btnMenuBuilderDeleteMenu").click(function (eventObj) {
            var postData = null;
            postData = {  MenuId: '@menuId' };

             showCommunicationPanelMessage('@Offtick.Web.OfftickWeb.Resources.UIMessages.Sending');

            $.ajax({
                type: 'POST',
                url: '@Url.Action("DeleteMenu")',
                 data: JSON.stringify(postData),
                 dataType: 'json',
                 processData: false,
                 contentType: 'application/json; charset:utf-8',
                 success: function (data, status) {
                     if (status == "success") {
                         alert(data);
                         window.location.replace( "@actionUrl");
                         //showCommunicationPanelMessage(data, 4000);
                     }
                 },
                 error: function (xhr, textStatus, error) {
                     var errorMessage = error || xhr.statusText;
                     alert(errorMessage);
                   //  showCommunicationPanelMessage(errorMessage + xhr.toString() + textStatus, 4000);
                 }
                
             });
        });
        $("#btnMenuBuilderChangeTitle").click(function (eventObj) {
            var postData = null;
            postData = { Title: $('#txtMenuBuilderEditTitle').val(), MenuId: '@menuId' };

            showCommunicationPanelMessage('@Offtick.Web.OfftickWeb.Resources.UIMessages.Sending');

             $.ajax({
                 type: 'POST',
                 url: '@Url.Action("EditMenuInfo")',
                data: JSON.stringify(postData),
                dataType: 'json',
                processData: false,
                contentType: 'application/json; charset:utf-8',
                success: function (data, status) {
                    if (status == "success") {
                        window.location.replace("@actionUrl");

                        //showCommunicationPanelMessage(data, 4000);
                    }
                },
                error: function (xhr, textStatus, error) {
                    var errorMessage = error || xhr.statusText;
                    showCommunicationPanelMessage(errorMessage + xhr.toString() + textStatus,4000);
                }
            });

        });
    });
</script>
<style type="text/css">
    table .ContainerTable{
        border-spacing:10px 10px;
        border-collapse: separate;
        border:1px solid black;
    }
      
</style>
<div >
    <div class="text-center">
        <h3 class="bg-primary">Edit Menu</h3> 
        
    </div>

    <div class="row">
        <div class="col-md-5">
             @if((Offtick.Core.EnumTypes.MenuType)Model.MenuType==  Offtick.Core.EnumTypes.MenuType.ParentMenu)
            {
                     <div class="TextHeaderL2">
                      Menu Orders
                    </div>
                      @Offtick.Web.OfftickWeb.Infrustracture.JQueryBuilder.SortableBuilder.GenerateSortable(
                        Model.Menu1.Select(e=> new Offtick.Web.OfftickWeb.Infrustracture.KeyValueItem(){Key=e.MenuId.ToString(),Value=e.Title}).ToList()
                        ,sortableId
                        ,liCssClasses
                        ,liSpanContentCssClass)
                     <script>
                         $(function () {
                             $("#@sortableId").sortable();
                             $("#@sortableId").disableSelection();
                         });
                     </script>

                     <button id="btnMenuBuilderEditMenuInfoChangeOrder" class="btn btn-default"  >
                         <span class="glyphicon glyphicon-sort-by-order"></span>Change Orders
                     </button>
                 
            }
        </div>

        <div class="col-md-3">
             <div class="TextHeaderL2">
                     Delete Menu
                </div>
                 <button  class="btn btn-default" id="btnMenuBuilderDeleteMenu">
                     <i class="glyphicon glyphicon-remove-circle"></i>Delete Current Menu
                 </button>
        </div>

         <div class="col-md-4">
             <div class="TextHeaderL2">
                     Edit Information
                </div>
             <p>
                 <span>Title:</span>
                  <input type="text" id="txtMenuBuilderEditTitle" value="@modelTitle" />
             </p>
               <button  id="btnMenuBuilderChangeTitle" class="btn btn-default" >
                                        <i class="glyphicon glyphicon-edit"></i>Change Title

                   </button>
             </div>

    </div>


    
   
</div>

OffTick Solution/System/Web/OfftickWeb/Areas/User/Views/MenuBuilder/MenuBuilderHeaderInfo.cshtml
@model Offtick.Data.Context.ExpertOnlinerContexts.Menu
@{
    bool commonCondition = Model != null && Model.MenuId != default(Guid);
    string menuTitle=commonCondition? Model.Title:" شما در منوی ریشه قرار دارید";
    string menuCreationDateTime = commonCondition ? Offtick.Core.Utility.PersianTools.PersianDateConvertor.ToKhorshidiDateTime(Model.LastDateTime) : "-";
    string parentTitle = commonCondition && Model.Menu2 != null ? Model.Menu2.Title : "-";
    int subMenuCount = commonCondition && Model.Menu1 != null ? Model.Menu1.Count : 0;
    string menuType = commonCondition ? Offtick.Web.OfftickWeb.Infrustracture.GlobalizationManager.GetMenuTypeCaptions((Offtick.Core.EnumTypes.MenuType)Model.MenuType) : "-";
}
<table class="table">
    <tr>
        <td>
              Title: @menuTitle
        </td>
        <td >
            Creation Date: @menuCreationDateTime
        </td>
        <td>
            Parent Title:@parentTitle
        </td>
        <td>
           Count Of Childs Menu: @subMenuCount
        </td>
        <td>
            Menu Type: @menuType
        </td>
    </tr>
</table>

OffTick Solution/System/Web/OfftickWeb/Areas/User/Views/MenuBuilder/MenuBuilderNoAddingMenuToDirectLink.cshtml
@{
    ViewBag.Title = "MenuBuilderNoAddingMenuToDirectLink";
}

<h3>امکان اضافه کردن زیر منو به یک منو از جنس لینک وجود ندارد</h3>