OffTick Solution/System/Web/OfftickWeb/Controllers/ImageGalleryController.cs
using Offtick.Business.Services.Managers;
using Offtick.Business.Web;
using Offtick.Web.OfftickWeb.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Offtick.Web.OfftickWeb.Controllers
{
    public class ImageGalleryController : BaseController
    {

        public ImageGalleryController(Offtick.Business.Services.Storage.DataContextContainer objectContext):base(objectContext)
        {
        }
        //
        // GET: /ImageGallery/

        public ActionResult Index(Guid garlleryId)
        {
            return View();
        }

        public ActionResult GalleriaViewer(string galleryId)
        {
            return PartialView("GalleriaViewer",(object)galleryId);
        }

        public ActionResult CarouselViewer(string galleryId) {
            Guid guidGalleryId;

                return PartialView("CarouselViewer",(object) galleryId);
            
        }
        public ActionResult CarouselViewer2(string galleryId)
        {
            Guid guidGalleryId;

            return PartialView("CarouselViewer2", (object)galleryId);

        }
        public ActionResult GalleriaImages(string galleryId)
        {
            if (!string.IsNullOrEmpty(galleryId))
            {
                var gallery = Offtick.Business.Services.Managers.GalleryManager.Instance.GetGallery(Guid.Parse(galleryId));
                if (gallery != null && gallery.GalleryImages != null)
                {
                    
                    Guid userId=gallery.MembershipUser.UserId;
                    var galleriaModel = (from img in gallery.GalleryImages
                                         select new GalleriaModel
                                         {
                                             description = img.Description,
                                             title = img.Title,
                                             imageId =img.ImageId,
                                             image = Offtick.Business.Services.Managers.GalleryManager.Instance.GetVirtualPathOfGalleryImage(img.ImageUrl, userId, false),
                                             thumb = Offtick.Business.Services.Managers.GalleryManager.Instance.GetVirtualPathOfGalleryImage(img.ImageUrl, userId, true),

                                         }).ToArray();

                    ImageGalleryViewerModel model = new ImageGalleryViewerModel()
                    {
                        GalleriaModels = galleriaModel,
                        GalleryId = gallery.GalleryId,
                        UserId = gallery.UserId,
                        UserName = gallery.MembershipUser.UserName,
                    };
                    return Json(model, JsonRequestBehavior.AllowGet);
                }
                
            }
            return null;
            
        }


       
    }
}

OffTick Solution/System/Web/OfftickWeb/Views/ImageGallery/CarouselViewer.cshtml
@model string
@{
    Guid galleryId;
    string userName = string.Empty;
    Guid userId=Guid.Empty;
    IList<Offtick.Data.Context.ExpertOnlinerContexts.GalleryImage> galleryImages = null;
                if (Guid.TryParse(Model, out galleryId))
                {
                    var gallery = Offtick.Business.Services.Managers.GalleryManager.Instance.GetGallery(galleryId);
                     galleryImages = gallery.GalleryImages.ToList();
                     userName = gallery.MembershipUser.UserName;
                     userId = gallery.MembershipUser.UserId;
                    
                 
                }
                string galleryWidth = !string.IsNullOrEmpty((string)ViewData["galleryWidth"]) ? (string)ViewData["galleryWidth"] : "100%";
                string galleryHeight = !string.IsNullOrEmpty((string)ViewData["galleryHeight"]) ? (string)ViewData["galleryHeight"] : "500px";
    
                
}
<style>
  .carousel-inner > .item > img,
  .carousel-inner > .item > a > img {
      width: 70%;
      margin: auto;
  }
  </style>

@if(galleryImages!=null && galleryImages.Count>0){
    <div id="myCarousel" class="carousel slide" data-ride="carousel" style="max-width:@galleryWidth;  max-height:@galleryHeight">
      <!-- Indicators -->
      <ol class="carousel-indicators">
          @for(int i=0;i<galleryImages.Count;i++){
              string classStr= i==0?"class='active'":string.Empty;
                <li data-target="#myCarousel" data-slide-to="@i" @classStr></li>
          }
      </ol>

      <!-- Wrapper for slides -->
          <div class="carousel-inner" role="listbox"  >
    
     

            @for (int i = 0; i < galleryImages.Count; i++)
            {
                var galleryImage=galleryImages[i];
                string classStr = i == 0 ? "active" : string.Empty;
                string imgUrl = Offtick.Business.Services.Managers.GalleryManager.Instance.GetVirtualPathOfGalleryImage(galleryImage.ImageUrl, userId, false);


               <div class="item @classStr" style="max-width:@galleryWidth;  max-height:@galleryHeight">
                    <img src="@imgUrl" alt="@galleryImage.Title"  >
                      <div class="carousel-caption">
                        <h3>@galleryImage.Title</h3>
                        <p>@galleryImage.Description</p>
                      </div>
                 </div>
            }
   


          <!-- Left and right controls -->
          <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
          </a>
          <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
          </a>
        </div>
    </div>
}

OffTick Solution/System/Web/OfftickWeb/Views/ImageGallery/CarouselViewer2.cshtml
@model string
@{
    Guid galleryId;
    string userName = string.Empty;
    Guid userId = Guid.Empty;
    IList<Offtick.Data.Context.ExpertOnlinerContexts.GalleryImage> galleryImages = null;
                if (Guid.TryParse(Model, out galleryId))
                {
                    var gallery = Offtick.Business.Services.Managers.GalleryManager.Instance.GetGallery(galleryId);
                     galleryImages = gallery.GalleryImages.ToList();
                     userName = gallery.MembershipUser.UserName;
                     userId = gallery.MembershipUser.UserId;
                }
                string galleryWidth = !string.IsNullOrEmpty((string)ViewData["galleryWidth"]) ? (string)ViewData["galleryWidth"] : "100%";
                string galleryHeight = !string.IsNullOrEmpty((string)ViewData["galleryHeight"]) ? (string)ViewData["galleryHeight"] : "500px";
    
                
if(galleryImages!=null){
        <div class="profile-slider-container">
            <section id="dg-container" class="dg-container">
                <div class="dg-wrapper">  
                    @for (int i = 0; i < galleryImages.Count; i++)
                        {
                            var galleryImage=galleryImages[i];
                            string classStr = i == 0 ? "active" : string.Empty;
                            string imgUrl = Offtick.Business.Services.Managers.GalleryManager.Instance.GetVirtualPathOfGalleryImage(galleryImage.ImageUrl,userId, false);
                            string description=galleryImage.Description;
                                    <a href="#"><img src="@imgUrl" title="@galleryImage.Title"></a>


                        
                        }
                </div>

                <nav>
                   <span class="dg-prev">
                       <i class="fa fa-step-backward" aria-hidden="true"></i>
                   </span>



                   <span class="dg-start">
                       <i class="fa fa-play" aria-hidden="true"></i>
                   </span>

                   <span class="dg-stop">
                       <i class="fa fa-pause" aria-hidden="true"></i>
                   </span>

                    <span class="dg-next">
                       <i class="fa fa-step-forward" aria-hidden="true"></i>
                   </span>
                </nav>
            </section>

        </div>
    }
}

OffTick Solution/System/Web/OfftickWeb/Views/ImageGallery/GalleriaViewer.cshtml
@model string
@{
    string galleriaID = "galleria" + Model;
    string galleryWidth = !string.IsNullOrEmpty((string)ViewData["galleryWidth"]) ? (string)ViewData["galleryWidth"] : "1024px";
    string galleryHeight = !string.IsNullOrEmpty((string)ViewData["galleryHeight"]) ? (string)ViewData["galleryHeight"] : "500px";
}
<style>
      #@galleriaID{height:@galleryHeight;width: @galleryWidth; }
</style>


<div id="@galleriaID" style="" class=" "></div>
<script type="text/javascript">
    $(function () {

   

        $.getJSON("@Url.Action("GalleriaImages", "ImageGallery", new { galleryId = Model })"
            , function (receiveData) {
                var galleriaData = receiveData.GalleriaModels;
                console.log(JSON.stringify(galleriaData));
                Galleria.loadTheme('/scripts/themes/classic/galleria.classic.min.js');
                Galleria.run('#@galleriaID', {
                    dataSource: galleriaData,
                    autoplay: 3000
                });
                
            }).fail(function ( jqxhr, textStatus, error ) {
                alert(jqxhr.responseText);
            });

        });
   
</script>

OffTick Solution/System/Web/OfftickWeb/Views/ImageGallery/Index.cshtml
@model Offtick.Data.Context.ExpertOnlinerContexts.Gallery
@{
    Layout = "";
}

  
    
    <script src="@Url.Content("~/Scripts/jquery-1.9.1.min.js")" ></script>
    <script src="@Url.Content("~/Scripts/jquery.unobtrusive-ajax.min.js")" ></script>
    <script src="@Url.Content("~/Scripts/jquery-ui-1.10.3.min.js")"></script>
    
     <script src="@Url.Content("~/Scripts/galleria-1.3.2.min.js")"></script>

  @Html.Partial("Slider",(object)"chaser603")