OffTick Solution/System/Web/OfftickWeb/Areas/Dr/Controllers/NewsController.cs
using Offtick.Business.Membership;
using Offtick.Business.Services.Managers;
using Offtick.Business.Services.Storage;
using Offtick.Business.Web;
using Offtick.Core.EnumTypes;
using Offtick.Web.OfftickWeb.Infrustracture;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization.Json;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;

namespace Offtick.Web.OfftickWeb.Areas.Dr.Controllers
{
    public class NewsController : BaseController
    {

        public NewsController(DataContextContainer obj)
            : base(obj )
        {
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult NewsArchive(string userId)
        {
            if (string.IsNullOrEmpty(userId))
                userId = MembershipManager.Instance.GetCurrentUserName();
            if (MembershipManager.Instance.ExistUser(userId))
            {
                return View(MembershipManager.Instance.GetCurrentUser().News);
            }
            else
                return null;
        }

        [HttpPost]
        [ValidateInput(false)]
        
        public ActionResult UploadNews()
        {
            var length = Request.ContentLength;
            string title = Request.Form["Title"];
            string body = Request.Form["Body"];
            string KeywordsJsonString = Request.Form["Keywords"];
            //JavaScriptSerializer JSS = new JavaScriptSerializer();

            //object obj = JSS.Deserialize<object>(Keywords);
            IList<string> keywordsList = new List<string>();
            var objects = Newtonsoft.Json.Linq.JArray.Parse(KeywordsJsonString); // parse as array  
            foreach (Newtonsoft.Json.Linq.JObject root in objects)
            {
                foreach (KeyValuePair<String, Newtonsoft.Json.Linq.JToken> app in root)
                {
                    keywordsList.Add((String)app.Value);
                }
            }



            if (Request.Files != null && Request.Files.Count != 0)
            {
                NewsManager.Instance.AddFile(1, title, body, MembershipManager.Instance.GetCurrentUserName(), keywordsList, Request.Files);
            }
            return null;
        }


        public ActionResult DeleteNews(Guid newsId)
        {
            DeleteStatus status = NewsManager.Instance.DeleteNews(newsId);
            string msg = UIActionStatusToUiMessage.ActionStatusToMessage(status);
            return Json(msg);
        }

        public ActionResult EditNews(Guid newsId)
        {
            var news = NewsManager.Instance.GetNews(newsId);
            return View(news);
        }

    }
}

OffTick Solution/System/Web/OfftickWeb/Controllers/ContentController.cs
using Offtick.Business.Services.Storage;
using Offtick.Business.Web;
using Offtick.Core.EnumTypes;
using Offtick.Web.OfftickWeb.Infrustracture;
using Offtick.Data.Context.ExpertOnlinerContexts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Offtick.Web.OfftickWeb.Controllers
{
    public class ContentController : BaseController
    {
        //
        // GET: /Content/

        public ContentController(DataContextContainer obj)
            : base(obj )
        {
            
        }


        public ActionResult Index(Guid menuId)
        {
            var menu = Offtick.Business.Services.Managers.ContentManager.Instance.GetMenu(menuId);
            if (!menu.IsSystemMenu)
                return View(menu);
            else
                return View(menu.MenuSystemic.SectionName, menu);

    
        }

        public ActionResult News(Guid newsId)
        {
            var news = Offtick.Business.Services.Managers.NewsManager.Instance.GetNews(newsId);
            return View(news);
        }

        public ActionResult SubmitContactMessage(ContactMessage message)
        {
            AddStatus status = Offtick.Business.Services.Managers.ContentManager.Instance.AddContactMessage(message);
            string msg = UIActionStatusToUiMessage.ActionStatusToMessage(status);
            return Json(msg);
        }

    }
}

OffTick Solution/System/Web/OfftickWeb/Views/Content/ContactUs.cshtml
@model Offtick.Data.Context.ExpertOnlinerContexts.Menu
@{
     Layout = "";
    string title =string.Empty;
    string body = string.Empty;
    string dateTime = string.Empty;
    string senderId=string.Empty;
    string recieverId=string.Empty;
    if(Model!=null){
        title = Model.MenuCaltures.Count>0?Model.MenuCaltures.First().Title:string.Empty;
        recieverId=Model.UserId.ToString();
        var currentUser=Offtick.Business.Membership.MembershipManager.Instance.GetCurrentUser();
        if(currentUser!=null)
        {
            senderId=currentUser.UserId.ToString();
        }
        dateTime=Model.LastDateTime.ToString("MMMM dd, yyyy");
        if (Model.MenuContents.Count != 0)
        {
            var content = Model.MenuContents.First();
            body =content.MenuContentCaltures.Count>0? content.MenuContentCaltures.First().Body: string.Empty;
        }
        
    }
    
    string txtSenderName="txtSenderName";
     string  txtSenderEmail="txtSenderEmail";
    string    txtSenderWebSite="txtSenderWebSite";
    string txtSenderMessage="txtSenderMessage";
        
    
}
<div class="wrapper">
					<div class="row-fluid">
						<div class="span12">
							
							<div id="main-col">
								
								<div class="entry-box">
									<div class="entry-thumb">
										@*<img src="@Url.Content("Content/themes/Nictitate/placeholders/post-image/post-24.jpg")" alt="" />*@
									</div>
									<header>                                	
										<h1 class="entry-title">@title<span></span></h1>
									@*	<span class="entry-date"><span data-icon="&#xe276;"></span>@dateTime</span>*@
									</header>
                                    @Html.Raw(body)
                                   
									
								</div><!--entry-box-->
								
								<div id="respond" dir="rtl">
									<h3>پیام خود را برای ما ارسال نمایید<span data-icon="&#xe014;"></span></h3>               
									<div id="comments-form" class="clearfix" >                
										<div class="comment-left">
											<p class="textarea-block">                        
												<label class="required" for="comment_message">متن پیام <span>(اجباری):</span></label>
												<textarea rows="6" cols="88" id="@txtSenderMessage" name="message"></textarea>
											</p>
										</div>
                                        <div class="comment-right">
											<p class="input-block">
												<label class="required" for="txtSenderName">نام <span>(اجباری):</span></label>
												<input type="text" class="valid" name="name" id="@txtSenderName" value="">
											</p>
											<p class="input-block">
												<label class="required" for="txtSenderEmail">ایمیل <span>(اجباری):</span></label>
												<input type="email" class="valid" name="email" id="@txtSenderEmail" value="">
											</p>
											<p class="input-block">                                                
												<label class="required" for="txtSenderWebSite">آدرس وب سایت:</label>
												<input type="text" id="@txtSenderWebSite" value="" class="valid" name="url">                                                
											</p>
											
										</div>
										
										<div class="clear"></div>
										<p class="comment-button">                    
											<input type="submit" id="btnSubmitContactUs" value="ارسال پیام">
										</p>
																					   
									</div>
									<div id="response"></div>
								</div><!--respond-->
								
							</div><!--main-col-->
							
						
							
							<div class="clear"></div>
							
						</div><!--span12-->
					</div><!--row-fluid-->                
				</div><!--wrapper-->

   <script type="text/javascript">
        $(function () {
            $("#btnSubmitContactUs").click(function (eventData) {


                var postData = null;

                postData = { RecieverUserId: "@recieverId", SenderUserId: "@senderId", SenderName: $('#@txtSenderName').val(), Email: $('#@txtSenderEmail').val(), WebSite: $('#@txtSenderWebSite').val(), Comment: $('#@txtSenderMessage').val() };



                 $.ajax({
                     type: 'POST',
                     url: '@Url.Action("SubmitContactMessage","Content")',
                data: JSON.stringify(postData),
                dataType: 'json',
                processData: false,
                contentType: 'application/json; charset:utf-8',
                success: function (data, status) {
                    if (status == "success") {
                        alert(data);
                    }
                },
                error: function (xhr, textStatus, error) {
                    var errorMessage = error || xhr.statusText;
                    alert(errorMessage + xhr.toString() + textStatus);
                }
            });

            });
        });
    </script>

OffTick Solution/System/Web/OfftickWeb/Views/Content/Index.cshtml
	@model Offtick.Data.Context.ExpertOnlinerContexts.Menu
@{
    Layout = "";
    
    
    
    string title = Model != null ? Model.Title : string.Empty;
    string body = string.Empty;
    string dateTime = string.Empty;
    if(Model!=null){
        
        dateTime=Model.LastDateTime.ToString("MMMM dd, yyyy");
        if (Model != null && Model.MenuContents.Count != 0)
        {
           var content = Model.MenuContents.First();
            body = content.Body;
        }
        
    }
}
<div class="page-title-wrapper">
				<div class="wrapper">
					<div class="row-fluid">
						<div class="span12">
							
							<div id="main-col">
								
								<div class="entry-box">
									@*<div class="entry-thumb">
										<img src="@Url.Content("Content/themes/Nictitate/placeholders/post-image/post-24.jpg")" alt="" />
									</div>*@
									<header>                                	
										<h1 class="entry-title" dir="rtl">@Html.Raw(title)<span></span></h1>
									@*	<span class="entry-date"><span data-icon="&#xe276;"></span>@dateTime</span>
										<span class="entry-comments"><span data-icon="&#xe06c;"></span><a href="#">@commentCount Comments</a></span>*@
									</header>
                                    @Html.Raw(body)
                                    
                                   @* <ul class="social-link clearfix">
										<li>Share this Post:</li>
										<li><a href="#" data-icon="&#xe168;"></a></li>
										<li><a href="#" data-icon="&#xe16c;"></a></li>
										<li><a href="#" data-icon="&#xe16f;"></a></li>
										<li><a href="#" data-icon="&#xe163;"></a></li>
										<li><a href="#" data-icon="&#xe178;"></a></li>
									</ul>*@
								@*	<footer class="clearfix">
										<p class="prev-post">
											<a href="#">&laquo;&nbsp;Older Article</a>
											<a class="article-title" href="#">Feature Post Tile</a>
											<span class="entry-date">Mar 29, 2013</span>
										</p>
										<p class="next-post">
											<a href="#">Next Article&nbsp;&raquo;</a>
											<a class="article-title" href="#">At menandri quaestio has</a>
											<span class="entry-date">Mar 29, 2013</span>                                
										</p>
									</footer>*@
								</div><!--entry-box-->
								
					
								
							</div><!--main-col-->
							
					
						</div><!--span12-->
					</div><!--row-fluid-->                
				</div><!--wrapper-->

OffTick Solution/System/Web/OfftickWeb/Views/Content/News.cshtml
	@model Offtick.Data.Context.ExpertOnlinerContexts.News
@{
    Layout = "";
    bool isNullModel = Model != null && Model.NewsCultures.Count > 0;
    
    string title = Model != null ? Model.NewsCultures.First().Title : string.Empty;
    string body = Model != null ? Model.NewsCultures.First().Body : string.Empty;
    string dateTime = string.Empty;
    
  
}

				
				
				<div class="wrapper">
					<div class="row-fluid">
						<div class="span12">
							
							<div id="main-col">
								
								<div class="entry-box">
									@*<div class="entry-thumb">
										<img src="@Url.Content("Content/themes/Nictitate/placeholders/post-image/post-24.jpg")" alt="" />
									</div>*@
									<header>                                	
										<h1 class="entry-title" dir="rtl">@title<span></span></h1>
									@*	<span class="entry-date"><span data-icon="&#xe276;"></span>@dateTime</span>
										<span class="entry-comments"><span data-icon="&#xe06c;"></span><a href="#">@commentCount Comments</a></span>*@
									</header>
                                    @Html.Raw(body)
								</div><!--entry-box-->
								
						
						</div><!--span12-->
					</div><!--row-fluid-->                
				</div><!--wrapper-->
            </div>
    